package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"GRPC/graphql-jwt-2/graph/model"
	"GRPC/graphql-jwt-2/internal/middleware"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	user, err := r.AuthStore.Register(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}

	// fake jwt
	fakeJWT := user.ID

	return &model.AuthPayload{
		Token: fakeJWT,
		User: &model.User{
			ID:    user.ID,
			Email: user.Email,
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	user, err := r.AuthStore.Login(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}

	// fake jwt
	fakeJWT := user.ID

	return &model.AuthPayload{
		Token: fakeJWT,
		User: &model.User{
			ID:    user.ID,
			Email: user.Email,
		},
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID := middleware.ForContext(ctx)
	if userID == "" {
		return nil, errors.New("unauthorized")
	}

	user, err := r.AuthStore.FindByID(ctx, userID)
	if err != nil {
		return nil, errors.New("user not found")
	}

	return &model.User{
		ID:    user.ID,
		Email: user.Email,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
