package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"

	"GRPC/graphql-jwt-1/auth"
	"GRPC/graphql-jwt-1/graph/model"

	"golang.org/x/crypto/bcrypt"
)

var users []*model.User

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, name string, email string, password string) (*model.AuthPayload, error) {
	for _, u := range users {
		if u.Email == email {
			return nil, errors.New("A user with this email already exists")
		}
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, err
	}

	user := &model.User{
		ID:       fmt.Sprintf("U%d", len(users)+1),
		Name:     name,
		Email:    email,
		PassHash: string(hash),
	}
	users = append(users, user)

	token, err := auth.GenerateToken(user.ID)
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{Token: token, User: user}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	var found *model.User
	for _, u := range users {
		if u.Email == email {
			found = u
			break
		}
	}
	if found == nil {
		return nil, errors.New("Invalid email or password")
	}

	if err := bcrypt.CompareHashAndPassword([]byte(found.PassHash), []byte(password)); err != nil {
		return nil, errors.New("Invalid email or password")
	}

	token, err := auth.GenerateToken(found.ID)
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{Token: token, User: found}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	var users []*model.User
*/
