// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Books []*Book `json:"books"`
}

type Book struct {
	ID     string  `json:"id"`
	Title  string  `json:"title"`
	Year   int32   `json:"year"`
	Author *Author `json:"author"`
}

type Mutation struct {
}

type NewBook struct {
	Title    string `json:"title"`
	Year     int32  `json:"year"`
	AuthorID string `json:"authorId"`
}

type Query struct {
}

type Subscription struct {
}
